#pragma once
#define RGOOutputEfficiencyModifiers 1.0
#define Terrain 1.0
#define OverseaPenalty 1.0
#define RGOThroughputEfficiencyModifiers 1.5
#define ProvinceInfrastructure 1.0
#define RGOSizeModifiers 1.0
#define ProvinceSize 2.0
#define WarExhaustion 0.0
#define MobilizedPenalty 0.0
#define Plurality 0.0
#define CON 0.0
#define PDEF_BASE_CON 0.1
#define INVENTION_IMPACT_ON_DEMAND 0.5
#define inventions 0.0
#define BASE_GOODS_DEMAND 1.0
#define Economicpolicymodifiers 1.0
#define InputEfficeny 1.0
#define FacktoryThroughputTecs 0.0
#define FacktoryEfficiencyTecs 0.0
#define EconomyEfficiencyTecs 0.0
#define AVGInfrastructureInState 0.0
#define LocalFactoryThroughput 0.0
#define TotalPopulationOfState 100000
